### ISSUE TITLE
Xindy for x86_64-linuxmusl

### ISSUE THREAD

**Issue by krumeich** [TeX-Live/texlive-source#17]
Sorry to bother you again with a request for a musl build: 

I'd like to use xindy under Alpine Linux. Unfortunately, there is no package for x86_64-linuxmusl. Is there any chance of providing one in the near future?

Thanks!

**Comment by norbusan** [comment]
Hi
well, someone has to follow the build descriptions as described in https://tug.org/texlive/build.html
It means building clisp (which is probably not that easy), and using clisp to build xindy.

**Comment by krumeich** [comment]
You're right. Building clisp under Alpine is quite daunting. There is a user contributed package, but I haven't managed to incorporate it into the build. A pity, but maybe someone more experienced than me finds a solution. Thanks anyway!

**Comment by svenper** [comment]
Another distro [using musl](/void-linux/void-packages/tree/master/srcpkgs/musl) is Void, that has a [clisp package](/void-linux/void-packages/blob/master/srcpkgs/clisp), which can be used on my system to build xindy. Perhaps those templates can be inspirational.

**Comment by krumeich** [comment]
@svenper That sounds promising. Would you be willing to share details about your xindy build? I constantly run into failed tests and out of memory errors. Thanks!

**Comment by svenper** [comment]
@krumeich

I take the “easy” way out and run `./configure` with arguments `--disable-xindy-docs --disable-xindy-rules`, and against all of the system libraries except `gc` and `libgs` (`--with-system-icu` etc.).

I take it xindy is working otherwise?

For reference: [TUG build guide](https://www.tug.org/texlive/build.html#xindy) and [BLFS texlive](http://www.linuxfromscratch.org/blfs/view/svn/pst/texlive.html) and [BLFS xindy](http://www.linuxfromscratch.org/blfs/view/svn/pst/xindy.html)
