### ISSUE TITLE
Is it possible to upgrade to lua5.4?

### ISSUE THREAD

**Issue by Freed-Wu** [TeX-Live/texlive-source#71]
Now https://github.com/TeX-Live/texlive-source/tree/trunk/libs/lua53/lua53-src use lua5.3.6.

Can it be upgrade?

**Comment by kberry** [comment]
As I recall, there are compatibility issues. I'll ask Luigi. For the future, FYI, the (public) luatex@tug.org mailing list is a better place to raise luatex questions.

**Comment by kberry** [comment]
Here is Luigi's reply:

[There are enough compatibility issues] to stay at 5.3.6 forever...

If we will make a transition, we will make an experimental  luatex /
luahbtex  5.4.6 (or whatever it will be)
together with the stock luatex /luahbtex so that the users can have the
time to adapt the code of their macros.

I think that the experimental luatex should be available at  least for one
texlive, better two , and fixing the bugs in this case is a mess...

People should understand that Lua in luatex  is "Lua for tex", it is a
custom Lua, it is not the "standard Lua"  + TeX. We have adapted and
modified the standard Lua  (not much, but enough).

we could stay here forever , there are custom Lua that are still based on Lua 5.2 or even  5.1.

luajit is a completely different issue.
